### ISSUE TITLE
Add podspec

### ISSUE THREAD

**Issue by marthinfreij** [madebybowtie/FlagKit#1]
Would be nice with Cocoapods support

**Comment by blommegard** [comment]
Woho, nu finns Carthage-support.
Ska undersöka Cocoapods med om det är lika smidigt.

**Comment by yanzhiwei147** [comment]
hey, we can support cocoapods also.

**Comment by blommegard** [comment]
Yay, finally done!

**Comment by yanzhiwei147** [comment]
well done! thank you very much.
