### ISSUE TITLE
Can't open on the latest Sketch version

### ISSUE THREAD

**Issue by mieram** [madebybowtie/FlagKit#10]
Version 3.3.3 (12081) is the latest release, but when opening the sketch file, a error message states that "Unable to open file. This document was created with a newer version of Sketch. Please upgrade to the latest version and try again."

**Comment by gellermark** [comment]
It's made with the Beta version of Sketch. If you download it - it won't overwrite the stable version but exist as a separate app. http://www.sketchapp.com/beta/

I hope they update the official version soon so we're not Beta-only :)

**Comment by mieram** [comment]
Ok, got it. Thanks :)
