### ISSUE TITLE
BY, RU etc.. We all stand for Ukraine, but I guess some of us need the official flags

### ISSUE THREAD

**Issue by MaximeDebarbat** [madebybowtie/FlagKit#108]
Alright, I understand the point simply I believe you should provide the official flags as an alternative.
https://cdn.jsdelivr.net/gh/umidbekk/react-flag-kit@1/assets/BY.svg
https://cdn.jsdelivr.net/gh/umidbekk/react-flag-kit@1/assets/RU.svg
...

**Comment by blommegard** [comment]
This is not from our repo.
