### ISSUE TITLE
Please add the flag for Sri Lanka

### ISSUE THREAD

**Issue by THPubs** [madebybowtie/FlagKit#13]
Sorry I can't make a pull request... I don't have sketch not even a mac. Please add the flag for Sri Lanka :

You can find the original file here : https://commons.wikimedia.org/wiki/File:Flag_of_Sri_Lanka.svg

![flag_of_sri_lanka svg](https://cloud.githubusercontent.com/assets/1212023/10415908/7c91d22e-701c-11e5-875c-1399165ccf66.png)

**Comment by gellermark** [comment]
It's now added to FlagKit! Thanx :+1:

**Comment by THPubs** [comment]
Perfect thanks! But the logo in the middle seems to be a bit not right when compared to the original one. :-)

**Comment by gellermark** [comment]
Well it's supposed to be 21x15 pixels so one have to simplify a lot to not have a super blurry result :)

**Comment by THPubs** [comment]
Ah cool! ok :-)
