### ISSUE TITLE
Can't build the framework for iOS

### ISSUE THREAD

**Issue by lexrus** [madebybowtie/FlagKit#17]
Even specifying the platform:
```carthage update --platform=ios```

Only the the framework for OS X built.
What's wrong?

**Comment by blommegard** [comment]
Oh, this is bad, I didn't realise that I broke the Carthage behaviour when adding multiple projects, will fix that asap, thanks!

**Comment by blommegard** [comment]
This should now be fixed, please verify! :)

**Comment by lexrus** [comment]
@blommegard Thank you. Now I can build FlagKit.framework for iOS target without any problem. But there's a warning :
```
*** Building scheme "FlagKit-OSX" in FlagKit.xcodeproj
*** WARNING: Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed
```

**Comment by blommegard** [comment]
Hum, :heart: code signing, think it should be fixed now anyway.

**Comment by lexrus** [comment]
:+1: Thanks a lot.
