### ISSUE TITLE
Ethiopia's emblem

### ISSUE THREAD

**Issue by moe-szyslak** [madebybowtie/FlagKit#19]
[Ethiopia's Flag 🇪🇹](https://en.wikipedia.org/wiki/Ethiopia#/media/File:Flag_of_Ethiopia.svg)
[Emblem ☆] (https://en.wikipedia.org/wiki/Ethiopia#/media/File:Coat_of_arms_of_Ethiopia.svg)

i don't know if it's pixelated or not but i see ✡ instead of ☆

**Comment by gellermark** [comment]
Thanx for noticing! :+1: Fixed now. 
However it has to be very simplified since it's for super small usage.
