### ISSUE TITLE
Flags for all App Store countries

### ISSUE THREAD

**Issue by claesjacobsson** [madebybowtie/FlagKit#21]
Thanks for FlagKit!

I would like to have all App Store countries in FlagKit. Flags currently missing (+/- the ones I missed):

AI Anguilla
BM Bermuda
FJ Fiji
GD Grenada
GY Guyana
KY Cayman Islands
MO Macau
MS Montserrat
SB Solomon Islands
SC Seychelles
SZ Swaziland
TC Turks and Caicos
VC St. Vincent and The Grenadines
VG British Virgin Islands
ZW Zimbabwe

**Comment by gellermark** [comment]
This is now done! Thanx for the feedback :+1:

**Comment by claesjacobsson** [comment]
Awesome!
