### ISSUE TITLE
1x images

### ISSUE THREAD

**Issue by AFK4now** [madebybowtie/FlagKit#22]
You have a beautiful collection. I see 2x and 3x images, but don't see any 1x - how do I go about finding 1x images? 

Thanks
AFK

**Comment by blommegard** [comment]
Hi, we are going to add 1x images as well, but as of now, the only way for you to get them is to export them yourself from the sketch-file.

This can be done by using the sketchtool:
`sketchtool export slices Sketch/FlagKit.sketch`
