### ISSUE TITLE
Missing Flags for Island Countries and Territories

### ISSUE THREAD

**Issue by nicolasgomollon** [madebybowtie/FlagKit#27]
Thanks for making FlagKit! I’m incorporating it into an open-source iOS app, and I noticed that the following island countries and territories are missing:

BV: [Bouvet Island](https://en.wikipedia.org/wiki/Bouvet_Island)
CC: [Cocos (Keeling) Islands](https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands)
CK: [Cook Islands](https://en.wikipedia.org/wiki/Cook_Islands)
CX: [Christmas Island](https://en.wikipedia.org/wiki/Christmas_Island)
FK: [Falkland Islands (Islas Malvinas)](https://en.wikipedia.org/wiki/Falkland_Islands)
GU: [Guam](https://en.wikipedia.org/wiki/Guam)
HM: [Heard & McDonald Islands](http://www.flags.net/HMCD.htm) (just a copy of the Australian national flag)
IO: [British Indian Ocean Territory](https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory)
MH: [Marshall Islands](https://en.wikipedia.org/wiki/Marshall_Islands)
MP: [Northern Mariana Islands](https://en.wikipedia.org/wiki/Northern_Mariana_Islands)
NF: [Norfolk Island](https://en.wikipedia.org/wiki/Norfolk_Island)
PN: [Pitcairn Islands](https://en.wikipedia.org/wiki/Pitcairn_Islands)
UM: [United States Minor Outlying Islands](https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands) (just a copy of the US flag)
VI: [United States Virgin Islands](https://en.wikipedia.org/wiki/United_States_Virgin_Islands)

**Comment by ramakanthdorai** [comment]
Adding to the missing flags

AS: [American Samoa](https://en.wikipedia.org/wiki/American_Samoa)
IM : [Isle of Man](https://en.wikipedia.org/wiki/Isle_of_Man)
PS : [Palestine Territories](https://en.wikipedia.org/wiki/Palestinian_territories) 
CW : [Curacao](https://en.wikipedia.org/wiki/Cura%C3%A7ao)
SS : [South Sudan](https://en.wikipedia.org/wiki/South_Sudan)
ZM : [Zambia](https://en.wikipedia.org/wiki/Zambia)
GF : [French Guiana] (https://en.wikipedia.org/wiki/French_Guiana)
PF : [French Polynesia] (https://en.wikipedia.org/wiki/French_Polynesia)
FT : [French Southern Territories] (https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands)
LK : [Sri Lanka](https://en.wikipedia.org/wiki/Sri_Lanka)
NR : [Nauru](https://en.wikipedia.org/wiki/Nauru)
GP : [Guadeloupe] (https://en.wikipedia.org/wiki/Guadeloupe)

**Comment by DavidODW** [comment]
Great library and thanks for developed it. I want to use it for my learning and I found that some countries and territories are still missing:

CW : [Curaçao](https://en.wikipedia.org/wiki/Cura%C3%A7ao)
SX : [Sint Maarten](https://en.wikipedia.org/wiki/Sint_Maarten)
KI : [Kiribati](https://en.wikipedia.org/wiki/Kiribati)
CC : [Cocos(Keeling) Islands](https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands)
CX : [Christmas Island](https://en.wikipedia.org/wiki/Christmas_Island)
NR : [Nauru](https://en.wikipedia.org/wiki/Nauru)
NF : [Norfolk Island](https://en.wikipedia.org/wiki/Norfolk_Island)
GL : [Greenland](https://en.wikipedia.org/wiki/Greenland)
GF : [French Guiana](https://en.wikipedia.org/wiki/French_Guiana)
GP : [Guadeloupe](https://en.wikipedia.org/wiki/Guadeloupe)
XK : [Kosovo](https://en.wikipedia.org/wiki/Kosovo)
YT : [Mayotte](https://en.wikipedia.org/wiki/Mayotte)
RE : [Reunion](https://en.wikipedia.org/wiki/R%C3%A9union)
BL : [Saint Barthélemy](https://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy)
MF : [Saint Martin](https://en.wikipedia.org/wiki/Saint_Martin)
PM : [Saint Pierre and Miquelon](https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon)
VA : [Vatican City](https://en.wikipedia.org/wiki/Vatican_City)
FK : [Falkland Islands](https://en.wikipedia.org/wiki/Falkland_Islands)
GG : [Guernsey](https://en.wikipedia.org/wiki/Guernsey)
GI : [Gibraltar](https://en.wikipedia.org/wiki/Gibraltar)
PS : [Palestine](https://en.wikipedia.org/wiki/Palestinian_territories)
JE : [Jersey](https://en.wikipedia.org/wiki/Jersey)
SJ : [Svalbard and Jan Mayen](https://en.wikipedia.org/wiki/Svalbard)
NU : [Niue](https://en.wikipedia.org/wiki/Niue)
PN : [Pitcairn Islands](https://en.wikipedia.org/wiki/Pitcairn_Islands)
AS : [American Samoa](https://en.wikipedia.org/wiki/American_Samoa)
IO : [British Indian Ocean Territory](https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory)
GU : [Guam](https://en.wikipedia.org/wiki/Guam)
MH : [Marshall Islands](https://en.wikipedia.org/wiki/Marshall_Islands)
VI : [US Virgin Islands](https://en.wikipedia.org/wiki/United_States_Virgin_Islands)
VU : [Vanuatu](https://en.wikipedia.org/wiki/Vanuatu)
PF : [French Polynesia](https://en.wikipedia.org/wiki/French_Polynesia)
NC : [New Caledonia](https://en.wikipedia.org/wiki/New_Caledonia)
WF : [Wallis and Futuna Islands](https://en.wikipedia.org/wiki/Wallis_and_Futuna)
ZM : [Zambia](https://en.wikipedia.org/wiki/Zambia)

**Comment by dafzthomas** [comment]
Brilliant pack! Some countries are also missing:

[ISO Wiki](https://en.wikipedia.org/wiki/ISO_3166-2:GB#Countries_and_province)

GB-WLS: Wales
GB-SCT: Scotland
GB-ENG: England

**Comment by gellermark** [comment]
Thanks for all the feedback and also apologies for the delay; a new version of FlagKit is on it's way! 

The goal is to release all these flags and some more during WWDC, stay tuned.

**Comment by paddykontschak** [comment]
GB-NIR: Northern Ireland is also missing!

**Comment by gellermark** [comment]
@paddykontschak As far as I understand things there is no official flag of Norther Ireland anymore? :/

**Comment by blommegard** [comment]
v1.1 is now released with all these flags, enjoy!
