### ISSUE TITLE
Uzbekistan flag

### ISSUE THREAD

**Issue by glebovsky** [madebybowtie/FlagKit#3]
Hi! 

Any chance to create Uzbekistan flag?   
![uzbekistan](https://cloud.githubusercontent.com/assets/1230158/10272868/3819ba90-6b48-11e5-9a5e-db8fa6a95256.png)

Thanks!

**Comment by gellermark** [comment]
It's done! 

I simplified it a bit to fit with the rest.

Thanx!

**Comment by glebovsky** [comment]
Looks just perfect! Thanks!
