### ISSUE TITLE
Feature Request: Northern Ireland flag

### ISSUE THREAD

**Issue by memfrag** [madebybowtie/FlagKit#33]
It would be awesome if you could add a GB-NIR flag to complete the GB set!

**Comment by gellermark** [comment]
It was actually a matter of not sure of what flag to use since we stumbled upon [this](https://en.wikipedia.org/wiki/Northern_Ireland_flags_issue).

But I guess we could use the flag used in the Euro 2016-tournament. Thanx for the feedback, I'll look in to it this week!

**Comment by gellermark** [comment]
Issue resolved with the latest update! 🙌
