### ISSUE TITLE
iOS 10 add some new countris or some have changed

### ISSUE THREAD

**Issue by qyhongfan** [madebybowtie/FlagKit#38]
AC=Ascension Island
BQ=Caribbean Netherlands
CP=Clipperton Island
CW=Curaçao
DG=Diego Garcia
EA=Ceuta & Melilla
IC=Canary Islands
KP=North Korea
SS=South Sudan
SX=Sint Maarten
TA=Tristan da Cunha
XK=name=Kosovo

**Comment by blommegard** [comment]
CW, KP, SS, SX, XK already exists.

**Comment by blommegard** [comment]
Please add a comment in https://github.com/madebybowtie/FlagKit/issues/36 for the remains ones and they will be added to the queue.
