### ISSUE TITLE
Flag representing "International/World/Others"

### ISSUE THREAD

**Issue by paddykontschak** [madebybowtie/FlagKit#4]
**Example case:**
In a previous project I was creating a drop down menu with a handful of flags for the user to choose from and get the default country code for their phone number. The company only had official customers from these selected countries, however they wanted to give the user the chance to add their own country code in case they're currently on vacation in another country not officially catered to from the company.

**Idea:**
A flag that indicates something where the user could see "oh, that means global/other countries/etc" would be helpful. Unfortunately the world hasn't decided on an earth flag just yet (despite existing ideas, like [this](http://www.flagofplanetearth.com/) or [this](https://www.reddit.com/r/pics/comments/r9tjf/my_design_for_earths_flag/)), in my previous project I ended up combining the [UN flag's blue background](https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Nations.svg) and a slightly altered version of the [globe available in the wikimedia commons](https://commons.wikimedia.org/wiki/File:Globe_icon.svg).

**Comment by gellermark** [comment]
We added a flag with a "Globe" symbol that might work (WW)

**Comment by paddykontschak** [comment]
That's perfect, thanks!
