### ISSUE TITLE
Carthage build failed, OS X 10.11.6, Xcode 8, Swift 3.

### ISSUE THREAD

**Issue by aalenliang** [madebybowtie/FlagKit#40]
I'm using FlagKit for macOS project, programming in Swift 3.
My system is OS X 10.11.6, platform is Xcode 8, Carthage 0.18.
In my Cartfile, I wrote:
github "madebybowtie/FlagKit" "swift3"

When I run "carthage update" in my console, it always failed to build:

Failed to write to /Users/User/Documents/Projects/Lab/Project/Carthage/Build/Mac/FlagKit.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “FlagKit.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/User/Documents/Projects/Lab/Project/Carthage/Checkouts/FlagKit/DerivedData/FlagKit/Build/Products/Release-iphoneos/FlagKit.framework, NSUnderlyingError=0x7f89ce1c04f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

The 'FlagKit.framework' file actually exist in '/Release' folder, I tried "carthage update --platform Mac" got the same error.

Looking for help, Thanks a lot.

**Comment by aalenliang** [comment]
However after I tried "carthage update --platfrom iOS", it succeeded, and my /build/mac has the right contents. still feel weird.

**Comment by blommegard** [comment]
Did you find out what was wrong?

**Comment by aalenliang** [comment]
I tried few times, and succeeded accidentally. And never failed with the same reason again.

**Comment by aalenliang** [comment]
I did some research today, it turns out to be Carthage's issue.

Carthage seems to try to copy the file in 
"/Users/User/Library/Developer/Xcode/DerivedData/FlagKit-elyskaizpvzagzbknlniohvnpdaa/Build/Products/**Release-iphoneos**/FlagKit.framework"
to
".../MyProject/Carthage/Build/**Mac**/FlagKit.framework"
Which is obviously wrong thing to do.

According to current FlagKit project configuration, it builds framework for all platforms. After copying the framework to my project manually, it works fine.

**Comment by aalenliang** [comment]
I opened an issue in carthage.
https://github.com/Carthage/Carthage/issues/1513

**Comment by ikesyo** [comment]
See https://github.com/Carthage/Carthage/issues/1513#issuecomment-251543160.
