### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by edwardmp** [madebybowtie/FlagKit#47]
Is there a specific reason you removed the code part and integration with CocoaPods? The changes for Swift 3 are very little (just did this manually to keep it working).

**Comment by edwardmp** [comment]
@blommegard ?

**Comment by blommegard** [comment]
Yeah, I know the migration part is simple, but for every new version we have to make a release, test it for cocoapods and carthage, distribute and it was just taking more time than it was worth for us.

After all, this is just assets and peoples can just drag them into their project the way they want.
It's way easier for us to just distribute assets and have code examples on the wiki.

**Comment by edwardmp** [comment]
@blommegard 
I strongly urge you to reconsider. Yes we can just copy them in our project, but if you add new flags we have to update them manually and it's a pain to track down.

Use the community to help you. Also, I would not see a point in really explicitly testing for cocoapods and carthage unless you would have changed something major.

**Comment by blommegard** [comment]
@edwardmp We have now reintroduced support for Carthage and CocoaPods!

**Comment by edwardmp** [comment]
@blommegard, awesome, thanks. You can close this issue then.

**Comment by edwardmp** [comment]
@blommegard Follow-up question: any specific reason why the minimum iOS version is 10.0 for this pod?

**Comment by blommegard** [comment]
@edwardmp Hi! Yeah, we use `UIGraphicsImageRenderer` in https://github.com/madebybowtie/FlagKit/blob/master/Sources/Swift/FlagKit/UIImage.swift

We will strive to support the 2 latest OS versions, right now 10 and 11.
