### ISSUE TITLE
Missing country flags

### ISSUE THREAD

**Issue by omercanb** [madebybowtie/FlagKit#48]
Can you please add these flags?
Turkish Republic of Northern Cyprus
Antarctica
Western Sahara
Netherlands Antilles
Saint Helena
Saint Martin

**Comment by gusbemacbe** [comment]
Also add Abkhazia and Catalonia.

**Comment by dkk** [comment]
This library is already 4.5 MB on disc. I think only official countries should be included. Maybe additional pods could be created with regional flags, such as Basque Country, Catalonia, Quebec, etc.

**Comment by gusbemacbe** [comment]
The problem is that I need language flags.

**Comment by Arkkimaagi** [comment]
Using flags for languages is usually considered a poor approach. Flags != Languages There's plenty of material online about this.

**Comment by blommegard** [comment]
Saint Helena and Saint Martin was added in [2.0.1](https://github.com/madebybowtie/FlagKit/releases/tag/v2.0.1.)
We agree that only official countries should be included.

Would you please add the other ones to https://github.com/madebybowtie/FlagKit/issues/36, that way it is all gathered.
