### ISSUE TITLE
Header.png

### ISSUE THREAD

**Issue by BuenGenio** [madebybowtie/FlagKit#49]
How did you make the strethcy/wavy natural looking BE, PA & JP flags in the Header.png?

**Comment by gellermark** [comment]
Hi!

It's not really out of the box, but the basic is to use a SVG version and scale it up 4x. Then I've used a masking layer and then the a FlagKit SVG and another "effect" layer on top to make the shadowing and highlights. And voilá it's done. 

Here is a sketch file with the structure and layers to make it:
https://www.dropbox.com/s/abfsoch5hgbv4c2/Wavy%20Flag.sketch?dl=0

/m

**Comment by BuenGenio** [comment]
Brill, shame I'm not doing any iOS/Cocoa development - I'd love to submit a patch to add this as one of the effects :) Will see if I can come up with an NPM tool to convert SVGs with this effect added on! Looks bloody sexy though, I must say ;) Thanks!

**Comment by mashfreddie** [comment]
Was about to ask the same, that effect is wonderful!
