### ISSUE TITLE
Pod update still to v1.1.1

### ISSUE THREAD

**Issue by grifas** [madebybowtie/FlagKit#51]
Hi,

Pod update with ```pod 'FlagKit'``` is still to the 1.1.1 version and the ```[!] FlagKit has been deprecated``` appears at the end.

Have you an idea ?

**Comment by antontingstrom** [comment]
Hi,

Ensure your CocoaPods spec repositories are up to date by running `pod repo update`, and that you are using a recent version of CocoaPods. 

You should be able to update to version 2.0.1 using `pod update FlagKit`, if you are relying on implicit version locking. If you have explicitly specified versions in your `Podfile`, set the version to `2.0.1`  and run `pod install`.

CocoaPods has a great guide explaining the difference between `pod update` and `pod install` in-depth at https://guides.cocoapods.org/using/pod-install-vs-update.html

I hope that helps!

**Comment by grifas** [comment]
Thank you for your response.

I'm getting this error:
```
[!] CocoaPods could not find compatible versions for pod "FlagKit":
In Podfile:
   FlagKit (~> 2.0.1)

   Specs satisfying the `FlagKit (~> 2.0.1)` dependency were found, but they required a higher minimum deployment target.
```

Is it possible the minimum target is 9.0 ?

**Comment by antontingstrom** [comment]
Unfortunately not, we are using iOS 10 APIs in FlagKit. See ![this comment](https://github.com/madebybowtie/FlagKit/issues/47#issuecomment-332489118) for more information.

You can always include the Asset Catalog from FlagKit manually in your project and perform any customizations of the flags in your own code 😊
