### ISSUE TITLE
Flag style ".waving"

### ISSUE THREAD

**Issue by bnfrnz** [madebybowtie/FlagKit#54]
Hi! Just wondering... is there a way to get the flags styled like the top ones in [https://github.com/madebybowtie/FlagKit/blob/master/Header.png](https://github.com/madebybowtie/FlagKit/blob/master/Header.png), with shade etc. (assuming that's not .roundedRect, .square, or .circle)?

**Comment by blommegard** [comment]
Hi!

it is described in this issue: https://github.com/madebybowtie/FlagKit/issues/49

**Comment by bnfrnz** [comment]
Wow... that was quick.

Thanks, this is exactly what I need. However, my Sketch license is two years old and I'm getting "This document was created with a newer version of Sketch. Please upgrade to the latest version and try again." when I try to open your file.

I can create the shades myself but I really think you did a great job on those. Could I trouble you to share the Sketch layer as svg when you have a sec? Or is it more complex with multiple layers? No worries then...

Thanks either way!
