### ISSUE TITLE
Greece GR flag missing one blue stripe.

### ISSUE THREAD

**Issue by lance-at-flow** [madebybowtie/FlagKit#63]
Should be 5 blue + 4 white. Attaching corrected PNG and SVG. Thanks!

![greece-gr](https://user-images.githubusercontent.com/22038431/38209887-b33e61fe-3683-11e8-9b3c-722524d8afa6.png)
[greece-gr.svg.zip](https://github.com/madebybowtie/FlagKit/files/1868972/greece-gr.svg.zip)

**Comment by gellermark** [comment]
Hi! The missing stripe is a compromise I had to do to keep the look and feel of the flag within the pixel grid that FlagKit is built from. In your suggested solution the stripes end up on half pixels. FlagKit is meant to be used in small sizes so pixel perfection is key and sometimes wins over accuracy in the actual flags. Most of the flags are tweaked in some way work in our pixel perfect world. :)

**Comment by lance-at-flow** [comment]
OK, that makes sense. Thanks @gellermark !
