### ISSUE TITLE
Flag representing "North America"

### ISSUE THREAD

**Issue by hellozimi** [madebybowtie/FlagKit#7]
This is an amazing repo, the flags looks really good.

I would love to see a flag representing North America. The one with a United States and Canada flag split diagonally.

Do you accept pull requests by the way?

![North America Flag](https://upload.wikimedia.org/wikipedia/en/e/e2/Flags_north_america.jpg)

**Comment by Haroenv** [comment]
This wouldn't be correct. North America is more than CA/US, and for now there are only country flags. There should be a whole new category for combinations then IMO.

**Comment by gellermark** [comment]
We will look in to this, vi actually need something similar for the project we're working on at the moment so we might add it soon.

**Comment by raulriera** [comment]
What @Haroenv said, North America is not only those countries

**Comment by gellermark** [comment]
I'm thinking a simplification of the continent shape.

**Comment by gellermark** [comment]
This is now done :+1:

**Comment by Haroenv** [comment]
This should be added in the realm as well :)

**Comment by blommegard** [comment]
@Haroenv Added to the readme, will get a new version of the libs out as well soon!
