### ISSUE TITLE
Xocde 11

### ISSUE THREAD

**Issue by hadi-alnehlawi** [madebybowtie/FlagKit#78]
When upgrading to Xcode11, the FlagKit throw an error:
"Distill Failed for unknown reason.
FlagKit .xcassets"

**Comment by blommegard** [comment]
Is the name of your bundle "FlagKit .xcassets"?

Does anything in [this thread](https://stackoverflow.com/questions/20580968/xcode-error-distill-failed-for-unknown-reasons) help you solve it?

**Comment by hadi-alnehlawi** [comment]
Hi,

yes it is FlagKit.xcassets , what do you think the issue is?

**Comment by hadi-alnehlawi** [comment]
I even tried to test the FlagKitDemo-iOS on same Xcode version 11 with same error result.

**Comment by hadi-alnehlawi** [comment]
Hi,

I managed to resolve the issue. it was because macOS Catalina beta version with xocde 11 production is not able to detect the bundle.
i downgrade it to Mojavi and gets back to work fine.
P.S. if you have Catalina beta version with Xocde 10 version, you will not get such bug. it is only if upgraded to Xocde 11 production version.

**Comment by blommegard** [comment]
Oh, interesting, thanks for the research! Hopefully this gets resolved with the Catalina GM.
