### ISSUE TITLE
Flag not Visible Storyboard

### ISSUE THREAD

**Issue by tallalj** [madebybowtie/FlagKit#85]
I am using 2.0
Installed via cocoa pods
Added a uiimage via storyboard
Used storyboard to select a flag from the image dropdown
The flag is not visible when the app is built. Even though the uiimage is visible, it just shouldn't render the flag, instead, it is empty.

But if I set the flag image, via code, in the same storyboard uiimage. The image is displayed without any issues.

**Comment by sinstrokes** [comment]
[]()

**Comment by blommegard** [comment]
I don't think it is supported to set images from a framework in storyboards:
https://stackoverflow.com/questions/48704502/how-to-set-image-in-storyboard-from-framework-assests
