### ISSUE TITLE
The Chinese flag is wrong, please don't use it!

### ISSUE THREAD

**Issue by nofishdesign** [madebybowtie/FlagKit#88]
The Chinese flag is wrong, please don't use it!

**Comment by denissamoilov** [comment]
> The Chinese flag is wrong, please don't use it!

Would you be more specific, what is wrong?

**Comment by nofishdesign** [comment]
This is the Chinese flag. Note that the four small stars are five-pointed stars; your picture is four-pointed[
![image](https://user-images.githubusercontent.com/72636870/95845097-56e6bc80-0d7c-11eb-8afa-b3d9e135c6eb.png)
](url)

**Comment by gellermark** [comment]
The icons are meant to be used in super small scales. The reasoning behind the four-point stars is that they get less blurry in comparison to the five-pointed stars. They are not meant to be seen in the scale you show.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/2034128/95846267-88935f80-0d4b-11eb-9365-5ac914f4accf.png">

With more detailed flags it would look even worse :)

**Comment by denissamoilov** [comment]
Totally agree with @gellermark , many flags have 4-pointed stars, because on smaller resolution it would't look like a circle/dot. That's why this library is much better than many others, because of low detailing. For example check Brazil flag, it doesn't have stars at all: https://github.com/madebybowtie/FlagKit/blob/master/Assets/PNG/BR%403x.png

**Comment by nofishdesign** [comment]
This is not about the display effect, the national flag is a symbol of a country！I hope you can fix it

**Comment by gellermark** [comment]
@nofishdesign I'm not trying to make exact representation of the flags, I want to make them recognisable and sharp for most screens. It's a balance act when deciding what to simplify and what to keep.

If you take a closer look at many of the other flags they are highly simplified to work in 15*21 pixels. If you choose to create your own version of any flag in addition to using FlagKit for the rest you can of course do so 👍

**Comment by zenorocha** [comment]
Hello there, I'm using FlagKit in one of my projects and I heard a similar complaint about this. I understand the thought process about keeping it that way, but still, I wanted to bring visibility that more people might be facing this problem.

**Comment by nofishdesign** [comment]
It is necessary for us to maintain consistency with our national flag and do not accept changes for any reason.

**Comment by denissamoilov** [comment]
@nofishdesign then this kit doesn't suit you :)

**Comment by nofishdesign** [comment]
It can't be used for some reasons; but I don't deny your work, this is a good kit.
